### PR TITLE
Bump

### PR DESCRIPTION
**Pull request by ocefpaf**
```
The current public release, libpng 1.6.24, fixes potential vulnerabilities in
apps that use the PNG_IMAGE_SIZE macro (not used within libpng itself) or that
use a custom row_stride value (in which case PNG_IMAGE_BUFFER_SIZE could overflow).
It also includes some optimizations and minor fixes.
```

### CODE REVIEW

**Comment by 183amir** [comment]
I think it would be a good idea to start pinning libpng on a patch version in other feedstocks and then update it here.

**Comment by ocefpaf** [comment]
Can you test that against your Mac? I tested this on Linux and Windows without a problem. Our pinnings seems to break only in https://github.com/conda-forge/matplotlib-feedstock/issues/41

@pelson or @jjhelmus do you have a Mac to test this too?

**Comment by 183amir** [comment]
No it doesn't just break there. It breaks on bob.io.image too but I have pinned on a patch version there since.

**Comment by ocefpaf** [comment]
> It breaks on `bob.io.image` too but I have pinned on a patch version there since.

Nice. So you ate safe there. Hopefully more people with Macs will be able to chime in. I wonder why that does not happen on Linux or Windows though :confused:

**Pull request merged**
